### PR TITLE
Resolving issue #1

### PR DESCRIPTION
**Pull request by stavros-zavrakas**
Resolving issue #1 . There are few modifications on the X11 specific makefile and few changes on the source code. Please before accepting can you try to build on a mac and on a windows machine? I am not able to test if I broke something or not.

### CODE REVIEW

**Comment by adricasti** [comment]
Thanks a lot for this. In general, in Git is better to create a new branch (For example `git checkout -b linux_build`) for fixing things or adding features and then send a pull request from your feature branch so they can be merged back into the master branch. I did just that, except that I used the `__linux__` preprocessor definition from [SourceForge](http://sourceforge.net/p/predef/wiki/OperatingSystems/) following a [StackOverflow question](http://stackoverflow.com/questions/5919996/how-to-detect-reliably-mac-os-x-ios-linux-windows-in-c-preprocessor)

Could you please check to see if this newer definition works so we keep it POSIX compliant?

**Comment by stavros-zavrakas** [comment]
It compiles without problems using the `__linux__` macro. As I told you it is the first time that I am using firebreath and trying to integrate a plugin. I am trying to integrate your plugin with google chrome but is not recognized. As I see google chrome is dropping the NPAPI. Is this the case that I am not able to load the plugin into chrome? This is the version that I have: Version 41.0.2272.76 (64-bit)

On the other hand the plugin it seems that is loaded normally on firefox but I am not able to test it using your test website: `http://plugin.cardid.org`.

As I see on the webcard.js script that you have and is checking if the plugin is installed there is this line `var plugin = navigator.plugins["Smart Card Browser Plugin"];`  but it seems that the name of the plugin that I have is this one `WebCard_x86_64` and not `Smart Card Browser Plugin`. Also in the showDownload function there is this line `if (navigator.platform == "Win32" || navigator.platform == "MacIntel") {`. My platform name is `Linux x86_64`. Can we adjust them a bit?

If you want you can add this file into git so that I can make the modifications.

**Comment by adricasti** [comment]
I created a [new issue](https://github.com/cardid/WebCard/issues/3) for the fact that the plugin crashes in Linux. The code you mention above needs to be fixed but I guess only _after_ we manage to get the plugin running in Linux. For the moment we can test with the local [test page](https://github.com/cardid/WebCard/blob/master/WebCard.html) that you can just double click to run.  Don't forget that the plugin needs to be copied in /usr/mozilla/plugins.

I also added a wiki page about [building in Linux](https://github.com/cardid/WebCard/wiki/Building-in-Linux)

**Comment by dgrizzla** [comment]
I'm getting the same error here, the browser hangs and then the plugin crash in the line reader.connect(2). I'm on linux 14.04 LTS

**Pull request closed without merging**
